# Generated by Django 5.1 on 2024-09-28 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve conter 11 dígitos numéricos.', regex='^\\d{11}$')])),
                ('telefone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Telefone deve conter 10 ou 11 dígitos numéricos.', regex='^\\d{10,11}$')])),
                ('funcao', models.CharField(max_length=100)),
            ],
        ),
    ]
