# Generated by Django 5.1 on 2024-09-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='epi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_epi', models.CharField(max_length=100)),
                ('funcao_usam', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tempo_uso', models.IntegerField()),
            ],
        ),
    ]
