# Generated by Django 5.1 on 2024-09-28 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis', '0002_epi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('funcao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField()),
                ('data_prevista_devolucao', models.DateField()),
                ('condicoes_equipamento', models.CharField(choices=[('Novo', 'Novo'), ('Usado', 'Usado'), ('Reparado', 'Reparado')], default='Novo', max_length=10)),
                ('status', models.CharField(choices=[('Devolvido', 'Devolvido'), ('Danificado', 'Danificado'), ('Perdido', 'Perdido')], max_length=10)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='epis.colaborador')),
            ],
        ),
        migrations.DeleteModel(
            name='Colaboradores',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='funcao_usam',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='tempo_uso',
        ),
        migrations.AddField(
            model_name='epi',
            name='funcoes',
            field=models.TextField(default='Não especificado'),
        ),
        migrations.AddField(
            model_name='epi',
            name='tempo_uso_recomendado',
            field=models.IntegerField(default=30, help_text='Tempo de uso recomendado em dias'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='epis.epi'),
        ),
    ]
