# Generated by Django 5.1 on 2024-09-28 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis', '0003_colaborador_entrega_delete_colaboradores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='funcao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epis.colaborador'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='condicoes_equipamento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epis.epi'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='epi',
            name='funcoes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='epi',
            name='tempo_uso_recomendado',
            field=models.IntegerField(),
        ),
    ]
