# Generated by Django 5.1 on 2024-09-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis', '0004_alter_colaborador_funcao_alter_entrega_colaborador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='condicoes_equipamento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
